import { useState, useEffect, useRef } from 'react';
import { motion } from 'framer-motion';
import { Star, Bookmark, BookmarkCheck, ExternalLink, Search, Video, FileText, File, Sparkles, Loader2, GraduationCap, X } from 'lucide-react';
import { useLocation, useNavigate } from 'react-router-dom';
import { resourcesApi, type ApiResource } from '@/lib/api';
import { toast } from 'sonner';

const typeIcons: Record<string, React.ElementType> = { Video, Article: FileText, PDF: File };

interface IncomingCourse { code: string; title: string; topics?: string[] }

export default function Resources() {
  const location = useLocation();
  const navigate = useNavigate();
  const [resources, setResources] = useState<ApiResource[]>([]);
  const [search, setSearch] = useState('');
  const [filterSubject, setFilterSubject] = useState('All');
  const [generating, setGenerating] = useState(false);
  const [activeCourse, setActiveCourse] = useState<IncomingCourse | null>(null);
  const autoGenerated = useRef(false);

  useEffect(() => {
    resourcesApi.list().then(d => setResources(d.resources)).catch(() => toast.error('Failed to load resources'));
  }, []);

  // Arrived here from "Study this course" / "Generate resources" elsewhere in the app.
  useEffect(() => {
    const state = location.state as { course?: IncomingCourse } | null;
    if (state?.course && !autoGenerated.current) {
      autoGenerated.current = true;
      setActiveCourse(state.course);
      setFilterSubject('All');
      generateResources(state.course);
      window.history.replaceState({}, '');
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [location.state]);

  const subjects = ['All', ...new Set(resources.map((r) => r.subject).filter(Boolean))];
  const filtered = resources.filter(
    (r) => (filterSubject === 'All' || r.subject === filterSubject) && r.title.toLowerCase().includes(search.toLowerCase())
  );

  const toggleBookmark = async (id: string) => {
    try {
      const { bookmarked } = await resourcesApi.toggleBookmark(id);
      setResources(prev => prev.map(r => r.id === id ? { ...r, bookmarked } : r));
    } catch { toast.error('Failed to update bookmark'); }
  };

  const generateResources = async (course?: IncomingCourse | null) => {
    setGenerating(true);
    try {
      const { resources: fresh } = await resourcesApi.generate(course || undefined);
      setResources(fresh);
      if (course) {
        setFilterSubject(`${course.code} — ${course.title}`);
        toast.success(`Resources generated for ${course.code} — ${course.title}`);
      } else {
        toast.success('Resources generated from your profile and materials');
      }
    } catch (err: unknown) {
      toast.error(err instanceof Error ? err.message : 'Failed to generate resources');
    } finally {
      setGenerating(false);
    }
  };

  const clearCourseFocus = () => {
    setActiveCourse(null);
    setFilterSubject('All');
  };

  return (
    <div className="p-4 lg:p-8 max-w-5xl mx-auto space-y-6">
      <div className="flex items-center justify-between gap-3">
        <h1 className="text-2xl font-bold text-foreground">Resources Hub</h1>
        <button onClick={() => generateResources(activeCourse)} disabled={generating}
          className="gradient-primary text-primary-foreground px-4 py-2 rounded-lg text-sm font-medium flex items-center gap-2 hover:opacity-90 transition disabled:opacity-60">
          {generating ? <><Loader2 className="h-4 w-4 animate-spin" /> Generating</> : <><Sparkles className="h-4 w-4" /> {activeCourse ? `Regenerate for ${activeCourse.code}` : 'Generate'}</>}
        </button>
      </div>

      {/* Course focus banner — shown when arriving from "Study this course" / "Generate resources" */}
      {activeCourse && (
        <motion.div initial={{ opacity: 0, y: -6 }} animate={{ opacity: 1, y: 0 }}
          className="bg-primary/5 border border-primary/20 rounded-xl p-4 flex items-center gap-3">
          <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center text-primary shrink-0">
            <GraduationCap className="h-5 w-5" />
          </div>
          <div className="flex-1 min-w-0">
            <p className="text-sm font-semibold text-foreground">Generated for {activeCourse.code} — {activeCourse.title}</p>
            <p className="text-xs text-muted-foreground">No study material was found for this course, so resources were generated from its syllabus topics instead.</p>
          </div>
          <button onClick={clearCourseFocus} className="p-1.5 rounded-lg hover:bg-muted text-muted-foreground hover:text-foreground transition shrink-0" title="Clear focus">
            <X className="h-4 w-4" />
          </button>
        </motion.div>
      )}

      <div className="flex flex-col sm:flex-row gap-3">
        <div className="relative flex-1">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
          <input type="text" placeholder="Search resources..." value={search} onChange={(e) => setSearch(e.target.value)}
            className="w-full pl-10 pr-4 py-2.5 rounded-lg border border-input bg-card text-sm text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring" />
        </div>
        <div className="flex gap-2 overflow-x-auto pb-1">
          {subjects.map((s) => (
            <button key={s} onClick={() => setFilterSubject(s)}
              className={`px-3 py-2 rounded-lg text-xs font-medium whitespace-nowrap transition ${filterSubject === s ? 'gradient-primary text-primary-foreground' : 'bg-muted text-muted-foreground hover:text-foreground'}`}>
              {s}
            </button>
          ))}
        </div>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
        {filtered.map((res, i) => {
          const Icon = typeIcons[res.type] || FileText;
          return (
            <motion.div key={res.id} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.05 }}
              className="bg-card rounded-xl p-5 shadow-card space-y-3">
              <div className="flex items-start justify-between">
                <div className="flex items-start gap-3 min-w-0">
                  <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center text-primary shrink-0">
                    <Icon className="h-5 w-5" />
                  </div>
                  <div className="min-w-0">
                    <p className="text-sm font-medium text-foreground">{res.title}</p>
                    <p className="text-xs text-muted-foreground truncate">{res.subject} · {res.duration}</p>
                  </div>
                </div>
                <button onClick={() => toggleBookmark(res.id)} className="text-accent hover:scale-110 transition-transform shrink-0">
                  {res.bookmarked ? <BookmarkCheck className="h-5 w-5" /> : <Bookmark className="h-5 w-5" />}
                </button>
              </div>
              {res.topic && (
                <span className="inline-block text-[11px] px-2 py-0.5 rounded-full bg-secondary/10 text-secondary font-medium">
                  Topic: {res.topic}
                </span>
              )}
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-1 text-xs text-accent">
                  <Star className="h-3.5 w-3.5 fill-current" /> {res.rating}
                </div>
                <span className="text-xs px-2 py-1 rounded-full bg-primary/10 text-primary">{res.type}</span>
              </div>
              <a href={res.url} target="_blank" rel="noopener noreferrer"
                className="w-full py-2 rounded-lg border border-border text-sm font-medium text-foreground flex items-center justify-center gap-2 hover:bg-muted transition">
                <ExternalLink className="h-4 w-4" /> Open Resource
              </a>
            </motion.div>
          );
        })}
      </div>

      {filtered.length === 0 && !generating && (
        <div className="text-center py-16">
          <FileText className="h-16 w-16 mx-auto text-muted-foreground/30 mb-4" />
          <p className="text-foreground font-medium">No resources yet</p>
          <p className="text-sm text-muted-foreground mt-1">
            {activeCourse ? `Generating study resources for ${activeCourse.code}…` : 'Generate blogs, topics, and study links from your course and uploaded materials, or pick "Generate resources" for a specific course from Recommendations or Materials.'}
          </p>
        </div>
      )}
    </div>
  );
}
